### ISSUE TITLE
接口 PddDdkGoodsDetailRequest 参数解析的时候会有问题

### ISSUE THREAD

**Issue by sxd37miao** [sc1994/JD_PDD.SDK.CSharpe#2]
`var dicDerive = GetType()
                .GetProperties()
                .Where(x =>
                {
                    if (x.Name == nameof(DebugInfo)) return false;
                    var val = x.GetValue(this);
                    if (val is string str)
                    {
                        return !string.IsNullOrWhiteSpace(str);
                    }
                    return val != null;
                })
                .ToDictionary(
                    x => ConvertExtend.UpperToUnderline(x.Name), x =>
                    {
                        return x.GetValue(this).ToString();
                    }
                   );`
` x.GetValue(this).ToString();//这个是数组 直接ToString()就是System.Int64[]`
![Snipaste_2020-07-13_14-12-04](https://user-images.githubusercontent.com/17269429/87276459-f80e6e80-c512-11ea-8b5f-86a65bbd2f05.jpg)
![Snipaste_2020-07-13_14-12-44](https://user-images.githubusercontent.com/17269429/87276465-fb095f00-c512-11ea-8a89-67e46ac84d49.jpg)

**Comment by sc1994** [comment]
需要在这判定item的类型，或许你能自己解决这个问题
